# Generated by Django 3.2.3 on 2021-06-20 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0008_auto_20210620_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(null=True, unique=True)),
                ('activities', models.TextField(null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='publisher',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='book',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='start_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='first_app.publisher', to_field='name'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(max_length=300, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='book',
            name='diary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='first_app.diary', to_field='day'),
        ),
    ]
