# Generated by Django 3.2.3 on 2021-06-20 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0009_auto_20210620_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='diary',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='first_app.diary', to_field='day'),
        ),
    ]
