# Generated by Django 3.2.3 on 2021-06-20 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0011_alter_book_publisher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='diary',
        ),
        migrations.DeleteModel(
            name='Diary',
        ),
    ]
