# Generated by Django 3.2.3 on 2021-06-20 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0012_auto_20210620_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='book',
            name='start_time',
        ),
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
