# Generated by Django 3.2.3 on 2021-06-20 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0014_auto_20210620_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='rating',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='first_app.publisher', to_field='name'),
        ),
    ]
