# Generated by Django 3.2.3 on 2021-06-20 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0015_auto_20210620_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.DateField(null=True, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='diary',
        ),
        migrations.RemoveField(
            model_name='book',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='book',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='rating',
        ),
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='Diary',
        ),
        migrations.AddField(
            model_name='book',
            name='comment',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='first_app.comments', to_field='comment'),
        ),
    ]
