# Generated by Django 3.2.3 on 2021-06-23 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0016_auto_20210620_1922'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.TextField(null=True, unique=True),
        ),
    ]
