# Generated by Django 3.2.3 on 2021-06-24 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0018_alter_comments_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['id'], 'verbose_name': 'Author'},
        ),
    ]
